import {
  Activity,
  Bike,
  BookOpen,
  Box,
  CircleDot,
  Cog,
  Compass,
  Cpu,
  Factory,
  FileText,
  Flame,
  Folder,
  Gauge,
  GitBranch,
  History,
  Rocket,
  Ruler,
  Search,
  Settings2,
  Shield,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Trophy,
  UserRound,
  Waves,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react"

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  bike: Bike,
  book: BookOpen,
  bookopen: BookOpen,
  box: Box,
  circledot: CircleDot,
  cog: Cog,
  compass: Compass,
  cpu: Cpu,
  factory: Factory,
  file: FileText,
  filetext: FileText,
  flame: Flame,
  folder: Folder,
  gauge: Gauge,
  gitbranch: GitBranch,
  history: History,
  rocket: Rocket,
  ruler: Ruler,
  search: Search,
  settings: Settings2,
  settings2: Settings2,
  shield: Shield,
  shoppingcart: ShoppingCart,
  sliders: SlidersHorizontal,
  slidershorizontal: SlidersHorizontal,
  sparkles: Sparkles,
  trophy: Trophy,
  user: UserRound,
  userround: UserRound,
  waves: Waves,
  wind: Wind,
  wrench: Wrench,
  zap: Zap,
}

export function getCategoryIcon(name?: string): LucideIcon {
  if (!name) return Folder
  const key = name.toLowerCase().replace(/[^a-z0-9]/g, "")
  return icons[key] ?? Folder
}

